#! /bin/bash

./netMHCpan -a HLA-A01:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0101_out.txt &
./netMHCpan -a HLA-A02:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0201_out.txt &
./netMHCpan -a HLA-A02:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0202_out.txt &
./netMHCpan -a HLA-A02:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0203_out.txt &
./netMHCpan -a HLA-A02:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0205_out.txt &
./netMHCpan -a HLA-A02:06 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0206_out.txt &
./netMHCpan -a HLA-A02:07 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0207_out.txt &
./netMHCpan -a HLA-A02:11 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0211_out.txt &
./netMHCpan -a HLA-A03:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A0301_out.txt &
./netMHCpan -a HLA-A11:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A1101_out.txt &
./netMHCpan -a HLA-A23:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2301_out.txt &
./netMHCpan -a HLA-A24:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2402_out.txt &
./netMHCpan -a HLA-A24:07 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2407_out.txt &
./netMHCpan -a HLA-A25:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2501_out.txt &
./netMHCpan -a HLA-A26:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2601_out.txt &
./netMHCpan -a HLA-A29:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2901_out.txt &
./netMHCpan -a HLA-A29:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A2902_out.txt &
./netMHCpan -a HLA-A30:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3001_out.txt &
wait $(jobs -p)
./netMHCpan -a HLA-A30:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3002_out.txt &
./netMHCpan -a HLA-A31:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3101_out.txt &
./netMHCpan -a HLA-A32:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3201_out.txt &
./netMHCpan -a HLA-A33:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3301_out.txt &
./netMHCpan -a HLA-A33:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3303_out.txt &
./netMHCpan -a HLA-A34:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3401_out.txt &
./netMHCpan -a HLA-A34:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3402_out.txt &
./netMHCpan -a HLA-A36:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A3601_out.txt &
./netMHCpan -a HLA-A66:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A6601_out.txt &
./netMHCpan -a HLA-A68:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A6801_out.txt &
./netMHCpan -a HLA-A68:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A6802_out.txt &
./netMHCpan -a HLA-A68:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A6803_out.txt &
./netMHCpan -a HLA-A74:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/A7401_out.txt &
./netMHCpan -a HLA-B07:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B0702_out.txt &
./netMHCpan -a HLA-B07:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B0705_out.txt &
./netMHCpan -a HLA-B08:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B0801_out.txt &
./netMHCpan -a HLA-B13:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1301_out.txt &
./netMHCpan -a HLA-B13:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1302_out.txt &
./netMHCpan -a HLA-B14:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1402_out.txt &
./netMHCpan -a HLA-B15:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1501_out.txt &
wait $(jobs -p)
./netMHCpan -a HLA-B15:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1502_out.txt &
./netMHCpan -a HLA-B15:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1503_out.txt &
./netMHCpan -a HLA-B15:10 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1510_out.txt &
./netMHCpan -a HLA-B15:16 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1516_out.txt &
./netMHCpan -a HLA-B15:18 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1518_out.txt &
./netMHCpan -a HLA-B18:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B1801_out.txt &
./netMHCpan -a HLA-B27:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B2705_out.txt &
./netMHCpan -a HLA-B35:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3501_out.txt &
./netMHCpan -a HLA-B35:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3502_out.txt &
./netMHCpan -a HLA-B35:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3503_out.txt &
./netMHCpan -a HLA-B35:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3505_out.txt &
./netMHCpan -a HLA-B35:12 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3512_out.txt &
./netMHCpan -a HLA-B37:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3701_out.txt &
./netMHCpan -a HLA-B38:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3801_out.txt &
./netMHCpan -a HLA-B38:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3802_out.txt &
./netMHCpan -a HLA-B39:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3901_out.txt &
./netMHCpan -a HLA-B39:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3905_out.txt &
./netMHCpan -a HLA-B39:06 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B3906_out.txt &
wait $(jobs -p)
./netMHCpan -a HLA-B40:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4001_out.txt &
./netMHCpan -a HLA-B40:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4002_out.txt &
./netMHCpan -a HLA-B40:06 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4006_out.txt &
./netMHCpan -a HLA-B42:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4201_out.txt &
./netMHCpan -a HLA-B44:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4402_out.txt &
./netMHCpan -a HLA-B44:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4403_out.txt &
./netMHCpan -a HLA-B45:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4501_out.txt &
./netMHCpan -a HLA-B46:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4601_out.txt &
./netMHCpan -a HLA-B48:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4801_out.txt &
./netMHCpan -a HLA-B49:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B4901_out.txt &
./netMHCpan -a HLA-B50:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5001_out.txt &
./netMHCpan -a HLA-B51:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5101_out.txt &
./netMHCpan -a HLA-B52:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5201_out.txt &
./netMHCpan -a HLA-B53:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5301_out.txt &
./netMHCpan -a HLA-B54:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5401_out.txt &
./netMHCpan -a HLA-B55:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5501_out.txt &
./netMHCpan -a HLA-B55:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5502_out.txt &
./netMHCpan -a HLA-B57:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5701_out.txt &
./netMHCpan -a HLA-B57:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5703_out.txt &
./netMHCpan -a HLA-B58:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5801_out.txt &
./netMHCpan -a HLA-B58:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B5802_out.txt &
wait $(jobs -p)
./netMHCpan -a HLA-B81:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/B8101_out.txt &
./netMHCpan -a HLA-C01:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0102_out.txt &
./netMHCpan -a HLA-C02:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0202_out.txt &
./netMHCpan -a HLA-C03:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0302_out.txt &
./netMHCpan -a HLA-C03:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0303_out.txt &
./netMHCpan -a HLA-C03:04 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0304_out.txt &
./netMHCpan -a HLA-C03:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0305_out.txt &
./netMHCpan -a HLA-C04:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0401_out.txt &
./netMHCpan -a HLA-C04:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0403_out.txt &
./netMHCpan -a HLA-C05:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0501_out.txt &
./netMHCpan -a HLA-C06:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0602_out.txt &
./netMHCpan -a HLA-C07:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0701_out.txt &
./netMHCpan -a HLA-C07:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0702_out.txt &
./netMHCpan -a HLA-C07:04 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0704_out.txt &
./netMHCpan -a HLA-C08:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0801_out.txt &
./netMHCpan -a HLA-C08:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C0802_out.txt &
./netMHCpan -a HLA-C12:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1202_out.txt &
./netMHCpan -a HLA-C12:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1203_out.txt &
./netMHCpan -a HLA-C14:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1402_out.txt &
./netMHCpan -a HLA-C14:03 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1403_out.txt &
./netMHCpan -a HLA-C15:02 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1502_out.txt &
./netMHCpan -a HLA-C15:05 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1505_out.txt &
./netMHCpan -a HLA-C16:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1601_out.txt &
./netMHCpan -a HLA-C17:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1701_out.txt &
./netMHCpan -a HLA-C18:01 -f ../data/NetMHCpan/input_peptides.txt -p -inptype 1  > ../data/NetMHCpan/output/C1801_out.txt &